export const FIELD_CATEGORIES = [
  { key: 'maklumat_asas', label: 'Maklumat Asas', icon: 'Type' },
  { key: 'pilihan', label: 'Pilihan', icon: 'ListChecks' },
  { key: 'maklumat_ahli', label: 'Maklumat Ahli (Auto Isi)', icon: 'UserCheck' },
  { key: 'dokumen', label: 'Dokumen & Lampiran', icon: 'Paperclip' },
  { key: 'kandungan', label: 'Kandungan Borang', icon: 'FileText' },
];

const baseInput = {
  showRequired: true,
  showPlaceholder: true,
  showHelpText: true,
  showLabel: true,
  needsOptions: false,
};

export const FIELD_TYPES = [
  // ── Maklumat Asas ──
  {
    ...baseInput,
    value: 'short_text',
    label: 'Nama / Teks',
    description: 'Teks pendek satu baris. Sesuai untuk nama, jawapan ringkas.',
    category: 'maklumat_asas',
    icon: 'Type',
    keywords: ['nama', 'teks', 'short', 'ringkas'],
  },
  {
    ...baseInput,
    value: 'long_text',
    label: 'Teks Panjang',
    description: 'Untuk penerangan panjang, alamat atau catatan terperinci.',
    category: 'maklumat_asas',
    icon: 'AlignLeft',
    keywords: ['teks panjang', 'penerangan', 'alamat'],
  },
  {
    ...baseInput,
    value: 'email',
    label: 'E-mel',
    description: 'Untuk alamat e-mel dengan pengesahan format automatik.',
    category: 'maklumat_asas',
    icon: 'Mail',
    keywords: ['emel', 'email', 'surat'],
  },
  {
    ...baseInput,
    value: 'phone',
    label: 'Telefon',
    description: 'Nombor telefon termasuk kod negara. Format telefon Malaysia.',
    category: 'maklumat_asas',
    icon: 'Phone',
    keywords: ['tel', 'phone', 'telefon', 'hp'],
  },
  {
    ...baseInput,
    value: 'identity_no',
    label: 'No. Kad Pengenalan',
    description: 'No. Kad Pengenalan 12 digit tanpa dash.',
    category: 'maklumat_asas',
    icon: 'CreditCard',
    keywords: ['ic', 'kad pengenalan', 'kp', 'mykad', 'nric'],
  },
  {
    ...baseInput,
    value: 'number',
    label: 'Nombor',
    description: 'Untuk input nombor seperti bilangan, kuantiti.',
    category: 'maklumat_asas',
    icon: 'Hash',
    keywords: ['nombor', 'kuantiti', 'bilangan'],
  },
  {
    ...baseInput,
    value: 'currency',
    label: 'Jumlah Wang (RM)',
    description: 'Untuk jumlah wang dalam Ringgit Malaysia.',
    category: 'maklumat_asas',
    icon: 'DollarSign',
    keywords: ['wang', 'rm', 'ringgit', 'harga', 'amaun'],
  },
  {
    ...baseInput,
    value: 'date',
    label: 'Tarikh',
    description: 'Untuk memilih tarikh daripada kalendar.',
    category: 'maklumat_asas',
    icon: 'Calendar',
    keywords: ['tarikh', 'kalendar', 'hari', 'bulan'],
  },
  {
    ...baseInput,
    value: 'address_my',
    label: 'Alamat',
    description: 'Alamat lengkap Malaysia: alamat, poskod, bandar, negeri.',
    category: 'maklumat_asas',
    icon: 'MapPin',
    keywords: ['alamat', 'rumah', 'surat-menyurat', 'address'],
    isAddress: true,
    showPlaceholder: false,
    showHelpText: false,
  },

  // ── Pilihan ──
  {
    ...baseInput,
    value: 'select',
    label: 'Dropdown',
    description: 'Senarai pilihan dalam menu jatuh. Pilih satu sahaja.',
    category: 'pilihan',
    icon: 'ChevronDown',
    keywords: ['dropdown', 'pilihan', 'menu', 'senarai'],
    needsOptions: true,
    showPlaceholder: true,
  },
  {
    ...baseInput,
    value: 'radio',
    label: 'Radio',
    description: 'Pilih satu pilihan daripada beberapa yang dipaparkan.',
    category: 'pilihan',
    icon: 'Circle',
    keywords: ['radio', 'pilih satu', 'bulatan'],
    needsOptions: true,
    showPlaceholder: false,
  },
  {
    ...baseInput,
    value: 'checkbox',
    label: 'Checkbox',
    description: 'Pilih lebih daripada satu pilihan.',
    category: 'pilihan',
    icon: 'CheckSquare',
    keywords: ['checkbox', 'pilih banyak', 'kotak'],
    needsOptions: true,
    showPlaceholder: false,
  },
  {
    ...baseInput,
    value: 'yes_no',
    label: 'Ya / Tidak',
    description: 'Soalan ya atau tidak. Toggle ringkas.',
    category: 'pilihan',
    icon: 'ToggleLeft',
    keywords: ['ya', 'tidak', 'yes', 'no'],
    showPlaceholder: false,
    showHelpText: false,
  },

  // ── Maklumat Ahli (Auto Isi) ──
  {
    ...baseInput,
    value: 'member_name',
    label: 'Nama Ahli (Auto Isi)',
    description: 'Nama penuh ahli akan diisi secara automatik daripada profil ahli.',
    category: 'maklumat_ahli',
    icon: 'User',
    keywords: ['nama ahli', 'auto isi', 'nama'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_identity_no',
    label: 'No. KP Ahli (Auto Isi)',
    description: 'No. Kad Pengenalan ahli akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'Fingerprint',
    keywords: ['ic ahli', 'kp ahli', 'kad pengenalan'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_address',
    label: 'Alamat Ahli (Auto Isi)',
    description: 'Alamat lengkap ahli akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'MapPin',
    keywords: ['alamat ahli', 'auto isi', 'rumah'],
    isMemberAutofill: true,
    isAddress: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_dob',
    label: 'Tarikh Lahir (Auto Isi)',
    description: 'Tarikh lahir ahli akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'CalendarDays',
    keywords: ['tarikh lahir', 'hari lahir'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_phone',
    label: 'No. Telefon Ahli (Auto Isi)',
    description: 'Nombor telefon ahli akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'Smartphone',
    keywords: ['tel ahli', 'telefon'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_email',
    label: 'E-mel Ahli (Auto Isi)',
    description: 'Alamat e-mel ahli akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'Inbox',
    keywords: ['emel ahli', 'email'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_member_no',
    label: 'No. Ahli (Auto Isi)',
    description: 'Nombor ahli akan diisi automatik daripada profil ahli.',
    category: 'maklumat_ahli',
    icon: 'IdCard',
    keywords: ['no ahli', 'nombor ahli', 'keahlian'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_position',
    label: 'Jawatan (Auto Isi)',
    description: 'Jawatan pekerjaan ahli akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'Briefcase',
    keywords: ['jawatan', 'position', 'kerja'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_employer',
    label: 'Majikan (Auto Isi)',
    description: 'Nama majikan atau syarikat ahli akan diisi automatik.',
    category: 'maklumat_ahli',
    icon: 'Building2',
    keywords: ['majikan', 'employer', 'syarikat'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_employment_no',
    label: 'No. Pekerja (Auto Isi)',
    description: 'Nombor pekerja ahli akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'Badge',
    keywords: ['no pekerja', 'employment', 'pekerja'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_bank',
    label: 'Nama Bank (Auto Isi)',
    description: 'Nama bank ahli akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'Landmark',
    keywords: ['bank', 'nama bank'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_bank_account',
    label: 'No. Akaun Bank (Auto Isi)',
    description: 'Nombor akaun bank ahli akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'CreditCard',
    keywords: ['akaun bank', 'no akaun'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_marital_status',
    label: 'Status Perkahwinan (Auto Isi)',
    description: 'Status perkahwinan ahli akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'Heart',
    keywords: ['status', 'perkahwinan', 'marital'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_department',
    label: 'Jabatan (Auto Isi)',
    description: 'Nama jabatan atau bahagian ahli akan diisi automatik.',
    category: 'maklumat_ahli',
    icon: 'Building2',
    keywords: ['jabatan', 'department', 'bahagian'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_spouse_name',
    label: 'Nama Pasangan (Auto Isi)',
    description: 'Nama pasangan ahli akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'Heart',
    keywords: ['pasangan', 'spouse', 'suami', 'isteri'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'member_spouse_phone',
    label: 'No. Telefon Pasangan (Auto Isi)',
    description: 'Nombor telefon pasangan akan diisi automatik daripada profil.',
    category: 'maklumat_ahli',
    icon: 'Phone',
    keywords: ['telefon pasangan', 'spouse phone'],
    isMemberAutofill: true,
    showPlaceholder: false,
    showHelpText: false,
  },

  // ── Dokumen & Lampiran ──
  {
    ...baseInput,
    value: 'file',
    label: 'Muat Naik Fail',
    description: 'Pemohon boleh muat naik fail dokumen seperti PDF atau imej.',
    category: 'dokumen',
    icon: 'Upload',
    keywords: ['muat naik', 'upload', 'fail', 'dokumen'],
    showPlaceholder: false,
  },
  {
    ...baseInput,
    value: 'signature',
    label: 'Tandatangan',
    description: 'Pemohon boleh menandatangani secara digital dalam borang.',
    category: 'dokumen',
    icon: 'Pen',
    keywords: ['tandatangan', 'signature', 'digital'],
    showPlaceholder: false,
  },

  // ── Kandungan Borang ──
  {
    ...baseInput,
    value: 'note',
    label: 'Nota',
    description: 'Nota teks ringkas untuk makluman atau penerangan.',
    category: 'kandungan',
    icon: 'StickyNote',
    keywords: ['nota', 'peringatan', 'info'],
    showLabel: false,
    showRequired: false,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'instruction_text',
    label: 'Arahan',
    description: 'Teks arahan untuk pemohon. Latar biru untuk perhatian.',
    category: 'kandungan',
    icon: 'Info',
    keywords: ['arahan', 'panduan', 'cara'],
    showLabel: false,
    showRequired: false,
    showPlaceholder: false,
    showHelpText: false,
  },
  {
    ...baseInput,
    value: 'agreement_checkbox',
    label: 'Persetujuan',
    description: 'Checkbox persetujuan terma dan syarat.',
    category: 'kandungan',
    icon: 'CheckSquare',
    keywords: ['persetujuan', 'terma', 'syarat', 'agreement'],
    showRequired: true,
    showPlaceholder: false,
    showHelpText: true,
  },
  {
    ...baseInput,
    value: 'office_use_box',
    label: 'Kotak Kegunaan Pejabat',
    description: 'Untuk diisi oleh pegawai koperasi. Cetakan sahaja.',
    category: 'kandungan',
    icon: 'FileText',
    keywords: ['kegunaan pejabat', 'pegawai', 'office'],
    showLabel: true,
    showRequired: false,
    showPlaceholder: false,
    showHelpText: false,
  },
];

export const FIELD_TEMPLATES = [
  {
    id: 'maklumat_pemohon',
    name: 'Maklumat Pemohon',
    description: 'Nama, No. KP, Tarikh Lahir, Telefon, E-mel',
    fieldCount: 5,
    fields: [
      { type: 'member_name', label: 'Nama Penuh', is_required: true },
      { type: 'member_identity_no', label: 'No. Kad Pengenalan', is_required: true },
      { type: 'member_dob', label: 'Tarikh Lahir', is_required: true },
      { type: 'member_phone', label: 'No. Telefon', is_required: true },
      { type: 'member_email', label: 'E-mel', is_required: false },
    ],
  },
  {
    id: 'maklumat_pekerjaan',
    name: 'Maklumat Pekerjaan',
    description: 'Jawatan, Majikan, No. Pekerja, Jabatan',
    fieldCount: 4,
    fields: [
      { type: 'member_position', label: 'Jawatan', is_required: true },
      { type: 'member_employer', label: 'Majikan', is_required: true },
      { type: 'member_employment_no', label: 'No. Pekerja', is_required: false },
      { type: 'member_department', label: 'Jabatan', is_required: false },
    ],
  },
  {
    id: 'maklumat_bank',
    name: 'Maklumat Bank',
    description: 'Nama Bank, No. Akaun Bank',
    fieldCount: 2,
    fields: [
      { type: 'member_bank', label: 'Nama Bank', is_required: true },
      { type: 'member_bank_account', label: 'No. Akaun Bank', is_required: true },
    ],
  },
  {
    id: 'maklumat_pasangan',
    name: 'Maklumat Pasangan',
    description: 'Nama dan No. Telefon Pasangan',
    fieldCount: 2,
    fields: [
      { type: 'member_spouse_name', label: 'Nama Pasangan', is_required: true },
      { type: 'member_spouse_phone', label: 'No. Telefon Pasangan', is_required: false },
    ],
  },
  {
    id: 'maklumat_alamat',
    name: 'Maklumat Alamat',
    description: 'Alamat lengkap ahli',
    fieldCount: 1,
    fields: [
      { type: 'member_address', label: 'Alamat Ahli', is_required: true },
    ],
  },
  {
    id: 'alamat_manual',
    name: 'Alamat (Manual)',
    description: 'Alamat lengkap untuk diisi manual',
    fieldCount: 1,
    fields: [
      { type: 'address_my', label: 'Alamat', is_required: true },
    ],
  },
];

export function getFieldTypeConfig(value) {
  return FIELD_TYPES.find((t) => t.value === value);
}

export function getCategoryFields(categoryKey) {
  return FIELD_TYPES.filter((t) => t.category === categoryKey);
}

export function searchFieldTypes(query) {
  const q = query.toLowerCase().trim();
  if (!q) return FIELD_TYPES;
  return FIELD_TYPES.filter((t) => {
    if (t.label.toLowerCase().includes(q)) return true;
    if (t.description.toLowerCase().includes(q)) return true;
    if (t.keywords.some((k) => k.includes(q))) return true;
    if (t.value.toLowerCase().includes(q)) return true;
    return false;
  });
}

export const MEMBER_FIELD_MAP = {
  member_name: 'full_name',
  member_identity_no: 'identity_no',
  member_address: 'address',
  member_dob: 'date_of_birth',
  member_phone: 'phone',
  member_email: 'email',
  member_member_no: 'member_no',
  member_position: 'position',
  member_employer: 'employer',
  member_employment_no: 'employment_no',
  member_bank: 'bank',
  member_bank_account: 'bank_account',
  member_marital_status: 'marital_status',
  member_department: 'department',
  member_spouse_name: 'spouse_name',
  member_spouse_phone: 'spouse_phone',
};
